---
version: 2
sphinx:
  configuration: docs/sphinx/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - "python -m pip install sphinx-rtd-theme sphinx-autodoc-typehints"

python:
  install:
    - path: .
      extra_requirements:
        - "docs"
