---
# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: ":pipeline: Generate steps"
    command: |
      set -eo pipefail

      python3 -m pip install pyyaml
      python3 .buildkite/generatesteps.py | buildkite-agent pipeline upload
  - wait: ~
    continue_on_failure: true
  - label: ":junit: Test results"
    agents:
      provider: gcp
      image: family/core-ubuntu-2204
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "junit/*-junit.xml"
          job-uuid-file-pattern: "(.*)-junit.xml"
          fail-build-on-error: true
          failure-format: file
